/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PressRouteImport } from './routes/press'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedReturnsNewRouteImport } from './routes/_authenticated/returns.new'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReturnsNewRoute = AuthenticatedReturnsNewRouteImport.update({
  id: '/returns/new',
  path: '/returns/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/press': typeof PressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRoute
  '/track-order': typeof TrackOrderRoute
  '/warranty': typeof WarrantyRoute
  '/wishlist': typeof WishlistRoute
  '/account': typeof AuthenticatedAccountRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/product/$id': typeof ProductIdRoute
  '/returns/new': typeof AuthenticatedReturnsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/press': typeof PressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRoute
  '/track-order': typeof TrackOrderRoute
  '/warranty': typeof WarrantyRoute
  '/wishlist': typeof WishlistRoute
  '/account': typeof AuthenticatedAccountRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/product/$id': typeof ProductIdRoute
  '/returns/new': typeof AuthenticatedReturnsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/press': typeof PressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRoute
  '/track-order': typeof TrackOrderRoute
  '/warranty': typeof WarrantyRoute
  '/wishlist': typeof WishlistRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/product/$id': typeof ProductIdRoute
  '/_authenticated/returns/new': typeof AuthenticatedReturnsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliates'
    | '/auth'
    | '/brands'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/press'
    | '/reset-password'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/sustainability'
    | '/track-order'
    | '/warranty'
    | '/wishlist'
    | '/account'
    | '/orders'
    | '/reports'
    | '/product/$id'
    | '/returns/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliates'
    | '/auth'
    | '/brands'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/press'
    | '/reset-password'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/sustainability'
    | '/track-order'
    | '/warranty'
    | '/wishlist'
    | '/account'
    | '/orders'
    | '/reports'
    | '/product/$id'
    | '/returns/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/affiliates'
    | '/auth'
    | '/brands'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/press'
    | '/reset-password'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/sustainability'
    | '/track-order'
    | '/warranty'
    | '/wishlist'
    | '/_authenticated/account'
    | '/_authenticated/orders'
    | '/_authenticated/reports'
    | '/product/$id'
    | '/_authenticated/returns/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AffiliatesRoute: typeof AffiliatesRoute
  AuthRoute: typeof AuthRoute
  BrandsRoute: typeof BrandsRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PressRoute: typeof PressRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WarrantyRoute: typeof WarrantyRoute
  WishlistRoute: typeof WishlistRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns/new': {
      id: '/_authenticated/returns/new'
      path: '/returns/new'
      fullPath: '/returns/new'
      preLoaderRoute: typeof AuthenticatedReturnsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReturnsNewRoute: typeof AuthenticatedReturnsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReturnsNewRoute: AuthenticatedReturnsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AffiliatesRoute: AffiliatesRoute,
  AuthRoute: AuthRoute,
  BrandsRoute: BrandsRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PressRoute: PressRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SustainabilityRoute: SustainabilityRoute,
  TrackOrderRoute: TrackOrderRoute,
  WarrantyRoute: WarrantyRoute,
  WishlistRoute: WishlistRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
